### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stupakov** [stupakov/data-zoom-d3#1]
# Proof of Concept
- [ ] pick better data
- [ ] make it work on a phone
- [ ] shopping
- [ ] universe
- [ ] wikipedia rabbit hole
- [ ] [this thing](http://bost.ocks.org/mike/treemap/)
- [ ] [shitty new york times thing](http://www.nytimes.com/packages/html/newsgraphics/2011/0119-budget/)
- [ ] be able to import a json file and make it zoomable immediately
# Level One
- [x] 2 level nesting
- [x] automatically set nesting level by counting ancestors with class node-container
- [x] allow clicking links 
- [ ] allow selecting text in zoomable DOM
- [ ] extract each div into a named partial
- [ ] html and css of each named partial should be together?
- [ ] allow summary and full version to have different aspect ratio
- [ ] smooth animation between summary and full using [ramjet](http://www.rich-harris.co.uk/ramjet/)
- [x] don't require surrounding elements by a div to specify that they are the summary or the full version
- [ ] fix fade animation
- [ ] infinite zoom
- [ ] links to anchors within page center and zoom to the element
# Level Two: Extract the Things Into Library
